### ISSUE TITLE
Django needs to serve bibliography content with `watchtower.html` template

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#105]
When Django serves the `watchtower.html` template, the bibliography (referred to as `biblio_obj.biblio`) - - it is empty. Here are the relevant lines from `templates/essays//watchtower.html` template:
https://github.com/enoren5/tarot_juicer/blob/cf0b8d627a37785aa37ba54cd447ea1c654ba7a7/templates/essays/watchtower.html#L38-L41 

Here is the class object declared inside the `essays/models.py`:
https://github.com/enoren5/tarot_juicer/blob/cf0b8d627a37785aa37ba54cd447ea1c654ba7a7/essays/models.py#L50-L54 

I’ve narrowed down the problem to `essays/views.py` at line number 34 in this `context`:
https://github.com/enoren5/tarot_juicer/blob/cf0b8d627a37785aa37ba54cd447ea1c654ba7a7/essays/views.py#L30-L34

That’s my best effort at telling Django to serve the bibliography text content for the `essays` app. It’s not working as I expect. I am expecting the biblio content to appear at the bottom of the web page. Instead, it is empty.

The experimental code with the problem described above can be found on the remote branch titled `meta-and-biblio-work` located [here](https://github.com/enoren5/tarot_juicer/tree/meta-and-biblio-work).

**Comment by pixamentory** [comment]
please show me your query for biblio_obj

Where you are fetching this??

**Comment by enoren5** [comment]
@UmarGit resolved the issue in this commit: https://github.com/enoren5/tarot_juicer/pull/106/commits/994d1cf7a8059caf8abf7a7d2f4bd74b351af55d

Thanks, Umar!
