### ISSUE TITLE
Non-ssl redirects

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#110]
https://DN.com successfully redirects to https://www.DN.com, which is great. But http://DN.com or http://www.DN.com does not redirect to https://DN.com. How do I ensure that when a web visitor enters my address without https: (only http), it successfully re-directs to the ssl address?

My Domain Name registrar is through Google. 

When setting up my DN, I followed these two guides:

- https://devcenter.heroku.com/articles/custom-domains
- https://stackoverflow.com/a/56919434/6095646

**Comment by umar-arq** [comment]
# Solution

> As we need to redirect both `example.com to www.example.com` and `www.example.com to example.com`, both from http to https. So we need to add record of our domain for both `www.example.com` and `example.com` in Heroku.

thank you @enoren5 brother

**Comment by enoren5** [comment]
I gave Umar permissions on Google Domain Names who added a CNAME record (I think). The issue is now solved. Thanks, @UmarGit!
