### ISSUE TITLE
Admin security

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#112]
For the Admin Dashboard: How do we enable a timeout when the admin user (or any user) makes 3 incorrect attempts? What recourse would the admin user (myself) have if I got locked out? Like how would I unlock myself?

**Comment by umar-arq** [comment]
# Question

> Do you want the security to be disabled for admin ?

**Comment by enoren5** [comment]
I'd like to implement a policy like fail2ban for the Admin Dashboard. I want the Admin Dashboard to be more secure, not less. I certainly do not wish to disable security for the admin users.

Say for example if the admin user enters their Dashboard credentials incorrectly 3 times, how do I prevent future attempts?

**Comment by enoren5** [comment]
There is a terrific mature Django app called [django-defender](https://github.com/jazzband/django-defender). Right now it requires Redis instead of Postgres and looks like it would increase costs on Heroku and might be challenging to setup. If at a future date I wish to add some more security, I'll take a closer look at django-defender.
