### ISSUE TITLE
How to switch DEBUG = True/False on the fly in prod?

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#121]
When prod breaks, how do I enable Django to temporarily show debugging data to help me troubleshoot when prod breaks? 

I tried switching the DEBUG config environment variable in the Heroku Admin Dashboard from “False” to “True” (which had no effect).

**Comment by alienware** [comment]
This is just my guess, the application seem to be overriding the environment variable DEBUG in the settings file [here](https://github.com/enoren5/tarot_juicer/blob/c62e66a647422fc7772fa0234052e5f190e142a0/tarot_juicer/settings.py#L36). You could,
1. Test it out by printing the value of `DEBUG` config inside your running application.
2. Set `DJANGO_DEBUG` to `True` and verify it the `INFO` logs start appearing.

**Comment by UmarGit** [comment]
### Hey @enoren5 brother

> You can switch the `DEBUG`  on the fly using `DJANGO_DEBUG` config variable (as we have implemented a configuration as you know). Check Below screenshot from `settings.py`


![Screenshot 2021-08-10 015725](https://user-images.githubusercontent.com/39865635/128773493-f800cd5d-a7f0-4776-abb9-65fffd6f3e7d.png)

**Comment by enoren5** [comment]
@UmarGit: Yes, this is the DEBUG switch. But to make toggle it on/off, I need to manually make the change in `settings.py`, commit to master, and push to staging/prod. That is cumbersome to handle. Instead my initial question was how to keep DEBUG settings as they are, but be able to turn debugging on/off in prod without hard coding changes in `settings.py`. 

alienware proposes one such solution by first checking the `DEBUG` config in prod (like with heroku-cli) with something like `$ echo $DJANGO_DEBUG` or `$ echo $DEBUG` and then using export to make the change. I haven't tested this yet, but I will at my next opportunity (which will be later this week).

**Comment by UmarGit** [comment]
> @UmarGit: Yes, this is the DEBUG switch. But to make toggle it on/off, I need to manually make the change in `settings.py`, commit to master, and push to staging/prod. That is cumbersome to handle. Instead my initial question was how to keep DEBUG settings as they are, but be able to turn debugging on/off in prod without hard coding changes in `settings.py`.
> 
> alienware proposes one such solution by first checking the `DEBUG` config in prod (like with heroku-cli) with something like `$ echo $DJANGO_DEBUG` or `$ echo $DEBUG` and then using `$ export DEBUG = True` to make the change. I haven't tested this yet, but I will at my next opportunity (which will be later this week).

Yes @enoren5 brother, need to try your method

**Comment by UmarGit** [comment]
Then we will implement a switch to toggle it on the fly, If your hypothesis is true

**Comment by enoren5** [comment]
The official Django docs specifically say to: "Never deploy a site into production with DEBUG turned on." ([Citation](https://docs.djangoproject.com/en/3.2/ref/settings/#debug)). So that is the final word. Issue Closed.
