### ISSUE TITLE
Discuss web analytics solution options and implement

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#123]
I need a web analytics solution which:

**1.** is free
**2.** shows web visitor ip address, location (country), web browser, operating system, native screen resolution, and time spent on specific pages. [Piwik/Matomo has this feature](https://imgur.com/Zh4In0m).
**3.** is easy to set up
 
Matomo meets all the criteria but Matomo is strictly for LAMP stacks. My project isn't a VPS LAMP stack. My project is deployed to Heroku. Is there any way to achieve Matomo's feature (described above) with other free/easy to set up services? Google Analytics is free and easy, but it doesn't have the web visitor tracking feature that Matomo has. 

What other options are there out there that are easy to implement and shows data like in the screenshot I shared above?

I am expecting my site to have very little daily traffic. But when I share a link to a blog post with a close personal friend privately over email or Facebook, I'd like to be able to see which web pages they've viewed and for how long until they closed his web browser window or navigated away. This is the extent of my needs. For my purposes, I am uninterested in analyzing 'conversions' or tracking 'sales' figures.

If Google Analytics has a plugin which meets my needs, then your task will be to set it up and implement it!

**Comment by enoren5** [comment]
I did take a look. It's appealing. How easy is it for you to set it up?

**Comment by UmarGit** [comment]
Awesome, Just need a `Google Analytics` Account and add myself to set it up on your behalf.

**Comment by enoren5** [comment]
I added your 303 gmail account to Google Analytics and granted you full permissions to make any change you need.

**Comment by enoren5** [comment]
Google Analytics implemented successfully in #129. Thanks, @UmarGit 

I can leverage these web address locations inside the Google Analytics platform to access the requirements outlined at the top of this issue:

https://analytics.google.com/analytics/web/#/p282329543/reports/dashboard?params=_u..nav%3Dmaui&r=lifecycle-engagement-overview&ruid=lifecycle-engagement-overview,life-cycle,engagement&collectionId=life-cycle

https://analytics.google.com/analytics/web/#/p282329543/reports/dashboard?params=_u..nav%3Dmaui&r=user-demographics-overview&ruid=user-demographics-overview,user,demographics&collectionId=user

https://analytics.google.com/analytics/web/#/p282329543/realtime/overview?params=_u..nav%3Dmaui&collectionId=user

(As a note to myself for future use, if I am logged into Google Chrome using drone4four, I may need to sign out completely and then relogin with the warden Google username.)
