### ISSUE TITLE
Prevent "Back" button functionality on Gateway for additional security

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#189]
On the "Portal" langing page, near the bottom, when a web visitor clicks the "Logout" link (or clicks "Home" from the menu in the nav-bar anyhere elsewhere on the site) and the web visitor is directed to "Gateway" page, clicking the `Back` button in the web browser should not be possible. Like, on the "Gateway" page, the web visitor should not be able to return to their previous location by pressing `Back` and instead should always be required to submit their passphrase again to return to the website.

**Comment by enoren5** [comment]
@abubakarA-Dot: I merged your PR #202 into master and pushed it up to Heroku both pipelines: `staging` and `prod`. The issue persists. When clicking on "Logout" on the portal page or "Home" in the navbar on one of the other pages, Django serves the gateway template but clicking "Back" is still permitted by Django when it should not be. You can see here:
 - https://tarot-prod.herokuapp.com/
 - https://tarot-testing.herokuapp.com/

(Passphrase to copy and paste = `YourMagicPassphrase`.)

You mentioned that the problem could be with middleware not updating. How does that work when I am certain that I've merged your changes into master and pushed all of it (middleware included) up to Heroku? Is there a way to look at the middleware on Heroku to verify that the latest middleware changes are reflecting?

To test these changes I'm using Microsoft Edge and have cleared the cookies and all website cache data. So it's _perfectly_ clean.

**Comment by abubakarA-Dot** [comment]
Hi @enoren5 
I have checked it on both pipelines, and only the logout feature is working on the testing pipeline and no other feature is working.
Please let me look into it and fix it properly so that it can work on live server as well.

**Comment by enoren5** [comment]
Resolved in PR's #202, #204, #205
