### ISSUE TITLE
Fix 500 error - - migrations issue with db.sqlite3 and Postgres

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#234]
Django is showing a 500 OperationalError (screenshot below) when serving these addresses:
* http://127.0.0.1:8000/how_to
* http://127.0.0.1:8000/about
* http://127.0.0.1:8000/essay_list

Your task is to get those three pages to render under these two contexts:
1. With db.sqlite3 running (binary attached to this Upwork proposal)
2. With remote PostgreSQL exported locally (in this format): 

```
$ export DATABASE_URL='postgres://USER:PASSWORD@HOST:PORT/NAME'`
```
I will provide you with the right private credentials for you to copy and paste into your local terminal shell after I accept your UpWork proposal. With these credentials exported properly you will have the ability to test making migrations and migrating. Please note and for emphasis (in case you don't already know), for this `export` to work you will need to use the command in the same VT as you are running the Django server in. If you export in a different local shell, then the right db instance won't work.

Your task is to first explain what is happening and why Django is serving this 500 error. Next, you need to resolve the issue by making what ever changes are necessary to get it working in the source code and then to also explain your rationale behind your solution.

![image](https://user-images.githubusercontent.com/6686723/235354788-ba2992af-4075-4919-9784-48afab3ae035.png)

**Comment by srtr0tsky** [comment]
Hello, I came by UpWork. Your project is open source?

**Comment by chinmayroy** [comment]
Please contact me for solving your issue

**Comment by yoandresaav** [comment]
I can resolve the issues with a professional solution.

**Comment by kaushikdobariya777** [comment]
I an resole this issue on priority basis.
