### ISSUE TITLE
Correct  broken static files

### ISSUE THREAD

**Issue by enoren5** [enoren5/tarot_juicer#74]
Static thumbnails (generators model) is not showing when Django serves tarot_keys.html template. 

You can view the issue by navigating here: https://tarot-juicer-next-iter.herokuapp.com/tarot_key/8#
and then selecting the red: “Show/Hide Album” button. As you can see, the thumbnails aren’t parsing.

Here is a screenshot pointing out the issue: https://i.imgur.com/cPWfmwI.jpg 

I tried running collect static in my heroku shell with `$ python manage.pt collectstatic` which produces this error: 

> File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 138, in collect raise processed whitenoise.storage.MissingFileError: The file 'css/compass/css3' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f0dc9b58d90>. The CSS file 'css/tarot_key.css' references a file which could not be found:  css/compass/css3
> Please check the URL references in this CSS file, particularly any relative paths which might be pointing to the wrong location. The specific object with the issue is declared at line 12 in `generators/models.py`: `tarot_card_thumbnail = models.ImageField(upload_to='thumbnails/')`

This error needs to be corrected.

**Comment by SalmanManzoor777** [comment]
Your image size is big so that's why not showing in the thumbnail . It will be resolve when you decrease your image size means if you have 500*500  change it to 100*100

**Comment by SalmanManzoor777** [comment]
![image](https://user-images.githubusercontent.com/47211417/108405806-5cc93e80-7243-11eb-94e6-830d582d5b46.png)

I resolve this error

**Comment by enoren5** [comment]
Resolved in #78.
